apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app: wordpress
spec:
  storageClassName: wordpress-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
