apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql # will be used as a value in
  labels: # WORDPRESS_DB_HOST in wordpress-deploy.yml
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
