apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-role-binding
  namespace: team-a
  labels:
    hnc.x-k8s.io/inherited: "true" # Allows propagation to child namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-role # The role we created earlier
subjects:
- kind: ServiceAccount
  name: viewer-sa
  namespace: team-a
