apiVersion: v1
kind: Pod
metadata:
  name: pod-example-for-secrets
spec:
  containers:
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: apikeyvol
        mountPath: "/tmp/secretpath"
  volumes:
  - name: apikeyvol
    secret:
      secretName: apikey
