apiVersion: v1
kind: Service
metadata:
  name: nginx-sts-demo
  labels:
    app: nginx-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-sts
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: web
spec:
  serviceName: nginx-sts-demo
  replicas: 8
  selector:
    matchLabels: 
      app: nginx-sts
  template: 
    metadata:
      labels:
        app: nginx-sts
    spec: 
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8 
        ports:
        - containerPort: 80
          name: web
