apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod-1
  namespace: production
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
