---
apiVersion: v1
kind: Pod
metadata:
  name: node-name-example
spec:
  nodeName: "k8s-worker-1"
  containers:
    - name: nginx
      image: nginx:1.20
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
