apiVersion: v1
kind: Pod
metadata:
  name: mysql-unsecret
spec:
  containers:
    - name: mysqldb
      image: mysql:5.7
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "Geheim123!"
      ports:
        - name: web
          containerPort: 3306
          protocol: TCP
