---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-server
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'

spec:
  rules:
    - host: www.dockerlabs.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service-cp
                port:
                  number: 80