apiVersion: v1
kind: Pod
metadata:
  name: kuard-nfs-demo
spec:
  volumes:
    - name: "kuard-data"
      nfs:
        server: nfs.dockerlabs.de
        path: "/var/nfs/general"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
