apiVersion: v1
kind: Pod
metadata:
  name: kuard-local-storage
spec:
  volumes:
    - name: 'www-data'
      hostPath:
        path: '/var/lib/www-data'
  containers:
    #- image: gcr.io/kuar-demo/kuard-amd64:1
    - image: nginx:1.24
      name: kuard
      volumeMounts:
        - mountPath: '/usr/share/nginx/html'
          name: 'www-data'
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
