kind: Pod
apiVersion: v1
metadata:
  name: eks-ebs-pv-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: eks-ebs-pv-claim