apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-stack
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress
data:
  WORDPRESS_DB_HOST: wordpress-mysql
