apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-sa
  namespace: wordpress-stack
  labels:
    app.kubernetes.io/name: wordpress
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: wordpress-stack
  labels:
    app.kubernetes.io/name: wordpress
automountServiceAccountToken: false