# Create PersistentVolume
# change the ip of NFS server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-volume
  labels:
    app: wordpress
    tier: frontend
    app.kubernetes.io/name: wordpress
spec:
  storageClassName: wordpress-data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.dockerlabs.de
    # Exported path of your NFS server
    path: '/var/nfs/wordpress'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
  labels:
    app: wordpress
    tier: mysql
    app.kubernetes.io/name: wordpress
spec:
  storageClassName: mysql-data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.dockerlabs.de
    # Exported path of your NFS server
    path: '/var/nfs/mysql'
