---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: wordpress-stack
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress
spec:
  storageClassName: mysql-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress-stack
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress
spec:
  storageClassName: wordpress-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
