---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zahlenhelfer/argocd-example-apps
    targetRevision: master
    path: guestbook
  destination:
    name: in-cluster
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
