apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable-pod
  namespace: qos-demo
spec:
  nodeName: k8s-node-1
  containers:
  - name: nginx
    image: nginx:1.24
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
