apiVersion: v1
kind: Pod
metadata:
  name: mysql-unsecret
spec:
  containers:
    - name: mysqldb
      image: mysql:5.7
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqldb
            key: root_password
      ports:
        - name: web
          containerPort: 3306
          protocol: TCP
