kind: Pod
apiVersion: v1
metadata:
  name: example-configmap-pod
spec:
  containers:
    - name: env-dbserver-configmap
      image: nginx:1.22
      env:
        - name: db_server_address
          valueFrom:
            configMapKeyRef:
              name: example-db-configmap
              key: database_uri
