apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    env: production
    sla: gold
    betreuer: Marcus
    project: pikachu
    dsgvo: ja
    costcenter: "88"
spec:
  containers:
    - name: nginx-webserver
      image: nginx:1.27
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
