---
apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod-2
  labels:
    env: production
    sla: gold
    admin: marcus
    project: pikachu
    costcenter: "88"
spec:
  containers:
    - name: nginx-webserver
      image: nginx:1.25
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
