---
apiVersion: v1
kind: Pod
metadata:
  name: mymultipod-1
spec:
  containers:
    - name: nginx-webserver
      image: nginx:1.22
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
    - name: fluentd
      image: fluentd
