apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod-ready
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      readynessProbe:
        httpGet:
          path: /healthy
          port: 8080
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
