apiVersion: v1
kind: Pod
metadata:
  name: kuard-res-demo
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      resources:
        limits:
          memory: '150Mi'
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
