apiVersion: v1
kind: Pod
metadata:
  name: kuard-req-demo
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      resources:
        requests:
          memory: '15000000M'
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
