apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard-rs
  labels:
    app: "kuard"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "kuard"
      foo: "bar"
      sla: "gold"
  template:
    metadata:
      labels:
        app: "kuard"
        sla: "gold"
        foo: "bar"
        costecenter: "666"
        owner: "marketing"
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:2"
