apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "kuard"
      foo: "bar"
  template:
    metadata:
      labels:
        app: "kuard"
        foo: "bar"
        sla: "gold"
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:2"
