---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard-rs-dup
  labels:
    app: "kuard"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kuard"
      foo: "bar"
  template:
    metadata:
      labels:
        app: "kuard"
        sla: "gold"
        foo: "bar"
        projectid: "666"
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:2"
