apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  selector:
    matchLabels:
      app: website
      test: service
  replicas: 5
  template:
    metadata:
      labels:
        app: website
        test: service
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:2
          ports:
            - containerPort: 8080
