apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  annotations:
    kubernetes.io/change-cause: 'TICKET 42'
spec:
  selector:
    matchLabels:
      app: website
      test: service
  replicas: 10
  template:
    metadata:
      labels:
        app: website
        test: service
    spec:
      containers:
        - name: kuard
          image: nginx:1.20
          ports:
            - containerPort: 8080
