apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-0815
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /srv/nfs/kubedata
    server: nfs.dockerlabs.de
  mountOptions:
    - hard
    - nfsvers=4.1
