apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-42
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: '/var/lib/kuard'
