apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-hostpath
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /var/host-path-test
